### ISSUE TITLE
fatal: Authentication failed

### ISSUE THREAD

**Issue by AskYous** [microsoft/Git-Credential-Manager-for-Mac-and-Linux#104]
I installed git-credential-manager on my mac. I then try to make it work with my repository hosted on Azure Devops: https://dev.azure.com/yousefshanawany..., but it never pops up a UI or anything and instead prompts me for a password in the terminal.

Is that supposed to happen? Isn't there supposed to be a popup?

I then proceed to give it my Azure Devops password, but it fails and says it's wrong. I even used the "Generate git credentials" feature in Azure Devops but it still gives the same output. I'm stuck.

![image](https://user-images.githubusercontent.com/791996/49620791-4fcc1780-f977-11e8-92c3-3f3006257889.png)

**Comment by nick-wegner** [comment]
> I installed git-credential-manager on my mac. I then try to make it work with my repository hosted on Azure Devops: https://dev.azure.com/yousefshanawany..., but it never pops up a UI or anything and instead prompts me for a password in the terminal.
> 
> Is that supposed to happen? Isn't there supposed to be a popup?
> 
> I then proceed to give it my Azure Devops password, but it fails and says it's wrong. I even used the "Generate git credentials" feature in Azure Devops but it still gives the same output. I'm stuck.
> 
> ![image](https://user-images.githubusercontent.com/791996/49620791-4fcc1780-f977-11e8-92c3-3f3006257889.png)

Did you figure anything out with this?  We are having the same problem.

**Comment by AskYous** [comment]
@nick-wegner Check out what we concluded on stackoverflow [here](https://stackoverflow.com/a/53664088/1404347). We found an uncomfortable complicated way around it and it worked. I can't really explain it.

**Comment by itlackey** [comment]
The stackoverflow post did not help. Anyone else have any luck fixing this?

**Comment by AskYous** [comment]
@itlackey can you share a screenshot of you attempting to clone the repository?

**Comment by itlackey** [comment]
I will if you need me to but it looks exactly like the one above.
git pull
[ask for password]
fatal: Authentication failed for xyz

**Comment by AskYous** [comment]
@itlackey Did you enter in the right repository url with your login username in it?

**Comment by chaluvadis** [comment]
Any update on this issues, I am not able to setup azure repos in my machine. 
![Screen Shot 2019-03-25 at 9 48 03 PM](https://user-images.githubusercontent.com/738511/54968196-d2d5a580-4f47-11e9-8dff-e791af0f0bc0.png)

**Comment by AskYous** [comment]
@chaluvadis use a personal access token. Makes it very easy! 👍

**Comment by chaluvadis** [comment]
@AskYous Thanks, it worked.

**Comment by jrbriggs** [comment]
I'd recommend trying [GCM Core's macOS preview release](https://github.com/microsoft/Git-Credential-Manager-Core#download-and-install)
