### ISSUE TITLE
Java is Required for 'brew install'

### ISSUE THREAD

**Issue by adamhill** [microsoft/Git-Credential-Manager-for-Mac-and-Linux#107]
It is alarming Java is required to install from 'brew'
--
~ brew install git-credential-manager
git-credential-manager: Java 1.6+ is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew Cask:
 brew cask install java
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html

At least the brewd version is OpenJDK :-) Is this intended or a hanging requirement?

**Comment by novak** [comment]
Do you have a version of Java installed outside of Homebrew?

**Comment by jrbriggs** [comment]
I'd recommend trying [GCM Core's macOS preview release](https://github.com/microsoft/Git-Credential-Manager-Core#download-and-install) which does not have this requirement.
