### ISSUE TITLE
Why do i need java to install a simple tool.

### ISSUE THREAD

**Issue by atilkan** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#109]
Do i need a truck to carry a box of glass?

**Comment by jakesays** [comment]
Might be because the tool is written in java. Just a guess.

**Comment by atilkan** [comment]
@jakesays Read all before guessing.

**Comment by novak** [comment]
A Java runtime is required for GCM to work.

**Comment by atilkan** [comment]
Sure.  if i did not know anything about this i would thing if other providers can do it without it.
