### ISSUE TITLE
Xcode Error When Installing From Brew

### ISSUE THREAD

**Issue by Axemasta** [microsoft/Git-Credential-Manager-for-Mac-and-Linux#119]
I noticed git credential manager hadn't been popping up & i had been getting manual prompts from git (which never seem to work).

I decided to reinstall git credential manager on my machine. I uninstalled it via brew:

- `git-credential-manager uninstall`
- `brew uninstall git-credential-manager`

then went to reinstall it:
- `brew install git-credential-manager`

I got the following output in the terminal:

```
brew install git-credential-manager
touch: /usr/local/Homebrew/.git/FETCH_HEAD: Permission denied
fatal: Unable to create '/usr/local/Homebrew/.git/index.lock': Permission denied
error: could not lock config file .git/config: Permission denied
Error: Your Xcode (1) is too outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/

Error: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.
```

Ignoring the permission error that is likely blocking the install (i'll fix that myself), the xcode error is interesting!

My Xcode is completely up to date (`/usr/bin/xcodebuild -version`):
```
Xcode 10.2.1
Build version 10E1001
```

**Comment by jrbriggs** [comment]
The xcode error doesn't appear to be related to the credential manager at all.

Nevertheless, I'd recommend you try [GCM Core's macOS preview release](https://github.com/microsoft/Git-Credential-Manager-Core#download-and-install) which should have a better experience on macOS.
