### ISSUE TITLE
Is there a way to brew install credential manager without Xcode 8?

### ISSUE THREAD

**Issue by cricketgeek** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#58]
re-installed brew on my mac and then tried to install credential manager and got the following error:

Error: Your Xcode (7.3) is outdated
Please update to Xcode 8.0.
Xcode can be updated from the App Store.

I would love to upgrade to Xcode 8 but our project won't currently build in it.

**Comment by yacaovsnc** [comment]
@cricketgeek sorry if I am wrong, but this seems like an issue with homebrew?  I need to look into what the problem really is.  

However at the meantime, this workaround may get you unblocked: you could download the latest 2.0.2 [release ](https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/releases), place the jar into a location that you see fit, and run `java -jar git-credential-manager-2.0.2.jar install`.  You can verify the credential section is updated in your `~/.gitconfig` file.
