### ISSUE TITLE
Doesn't work with debian Jessie

### ISSUE THREAD

**Issue by rakoenig** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#60]
Downloaded jar file and did the steps to install it. 

Now if I use git I get the following error:

Fatal: java.lang.IllegalArgumentException encountered.  Details:
tokenSecretStore can't be null

Hint: Running on an Xfce desktop.

**Comment by loslu** [comment]
I have the same problem. After enable the debug mode, I found this:
gnome-keyring library loaded, creating a password SCHEMA
Could not get default keyring info. GNOME Keyring is not available.
Return code: 6 description: error connecting gnome-keyring-daemon 

I tried to invoke gnome-keyring but it says: 
(gnome-keyring:24299): Gtk-WARNING **: cannot open display:

I think it's the reason on my PC without any display, hoping to get help...

**Comment by tylerjwatson** [comment]
I am also getting this issue.  GNOME 3.22 on Wayland.  I can confirm that `gnome-keyring-daemon` is running, and I can access other keyrings using _Passwords and Keys_.

**Comment by mcr** [comment]
Sigh. Can't we just use ssh public key authentication?

**Comment by leantk** [comment]
Thanks for reporting this bug. Sorry we haven't been able to get to it yet but it has been added to our backlog. 

@mcr you can use SSH to authenticate if you follow the instructions here: https://www.visualstudio.com/en-us/docs/git/use-ssh-keys-to-authenticate

I apologize again for the inconvenience and thanks reporting the issue,
-Leah

**Comment by yacaovsnc** [comment]
If you are still having problem with gnome-keyring, you can set this option to bypass it:
`git config --global credential.canFallBackToInsecureStore true`

If this is set, it will fallback to use insecure files to store your credential.  The generated file is at:
~/.VSTeamServicesAuthPlugin/insecureStore.xml

**Comment by sonvirgo** [comment]
@yacaovsnc  work ubuntu 16.04
