### ISSUE TITLE
Ubuntu server- only ssh available?

### ISSUE THREAD

**Issue by Laro88** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#61]
There seems to be a requirement for opening a browser session, how is this meant to work on pure shell servers? Any way to put in the auth string (token) somewhere?

**Comment by yacaovsnc** [comment]
The login process would fall back to "device flow", which prints out a login url and a unique code on the terminal, then you can login from any browser on any PC with that url and code.  The credential manager will continue once you login.  

However there is an issue with that flow currently that gnome-keyring is not accessible through ssh, and it will quit when it tries to save the credential securely.  To workaround this, you need to use [GCM4ML 1.7.1](https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/releases/tag/git-credential-manager-1.7.1), which will **insecurely** save your credential to a file which is only secured by unix file permission.    :(

**Comment by Laro88** [comment]
@yacaovsnc Is there any fix in the pipeline? I will try the 1.7.1 whenever I get back to this and see I can get that one to work :-)

**Comment by yacaovsnc** [comment]
It appears there is an option you can set:
`git config --global credential.canFallBackToInsecureStore true`

If this is set, it will fallback to use insecure files to store your credential.  The generated file is at:
~/.VSTeamServicesAuthPlugin/insecureStore.xml

This will make v2.0.3 GCM4ML works in ssh sessions just like v1.7.1 did.
