### ISSUE TITLE
Install Instructions on Ubuntu 16.04 Fail

### ISSUE THREAD

**Issue by jwdavidson** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#64]
This may be 3 separate issues:

1.  rpm --checksig --verbose git-credential-manager-2.0.2-1.noarch.rpm
returns a sha1 and md5 hash not what is shown

2. sudo rpm --install git-credential-manager-2.0.2-1.noarch.rpm
says that /bin/sh is not available (but it is) and to use Alien to do the install. then alien wants an --script tag to be added

3. git-credential-manager install
says it cannot find /bin/java (it is not located there in this distribution)

**Comment by leantk** [comment]
Hi @jwdavidson,

Thanks for reporting the issue. I am able to reproduce it on Ubuntu 16.04 so I am looking into a fix. To unblock you for now, you can follow these directions for installing with a jar instead: https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/blob/master/Install.md#installing-on-mac-or-linux-without-a-package-manager

Let me know if you have any issues with that. Sorry about the inconvenience but thanks again for pointing it out to us.

-Leah

**Comment by yacaovsnc** [comment]
On Ubuntu systems, please follow either the linuxbrew section or the section without package managers.  

I don't think we will spend the time to fix RPM on Ubuntu since the default package manager is APT, and we have workarounds.

**Comment by cglong** [comment]
@yacaovsnc Are there any plans to add this to APT? Ubuntu is a very popular distro and having to manually maintain a JAR or Linuxbrew for this is inconvenient.

**Comment by sebospc** [comment]
The issue persist in arch linux, but i found a solution :
`sudo rpm --dbpath $HOME/myrpmdb --nodeps -ivh XXX.rpm`
 from:  https://stackoverflow.com/a/12758298/7083464
