### ISSUE TITLE
Is there a way to add a personal access token?

### ISSUE THREAD

**Issue by Domysee** [microsoft/Git-Credential-Manager-for-Mac-and-Linux#68]
Is there a way to add a personal access token, generated in visualstudio.com, via the command line?

The reason I'd like to do this is that the authentication flow doesn't work for me when I try to checkout a repo. I get the code and the url, put the code in, then select my account, and from then on I'm always redirected, getting a prompt if I forgot my password. However, I cannot even enter the password, because the redirect happens as soon as I'm switching to the password field.

**Comment by jrbriggs** [comment]
Closing stale issues.
