### ISSUE TITLE
Error: Unrecognized version string '9+181' (Macos High Sierra, Java 9)

### ISSUE THREAD

**Issue by JoeyHerrington** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#69]
After installing, I get the following error while attempting to clone a repo:
```
Fatal: java.lang.IllegalArgumentException encountered.  Details:
Unreccognized version string '9+181'
fatal: credential helper '!/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java -Ddebug==false -Djava.net.useSystemProxies=true -jar /usr/local/Cellar/git-credential-manager/2.0.3/libexec/git-credential-manager-2.0.3.jar' told us to quit
```

I'm running High Sierra, Xcode 9, and Java 9 downloaded from Oracle's site.

Note when I run `java --version`, I get:
```
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java Hotspot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

It's clear to me that the fix is to uninstall this version of Java and install a different version, however, I know this can potentially happen again with anyone, and you guys ought to know this might be a thing!

**Comment by JoeyHerrington** [comment]
Note:
I dumped Java 9 and installed Java 8, and I everything worked just fine.

**Comment by felpel** [comment]
I stumbled on the same issue as @JoeyHerrington and installed JDK8 instead:
`brew cask install caskroom/versions/java8`

**Comment by drayfar** [comment]
Any update on this?

**Comment by JoeyHerrington** [comment]
Honestly, I haven't looked since I made this ticket... I downgraded JDK and never looked back!  I take it it's still an issue? I'd fix it, but I have no idea how contributing to a GitHub project works!

**Comment by pplboy** [comment]
the same question.. and i install java 10, and still error...last i install java 8.then all is ok..... :(

**Comment by novak** [comment]
version 2.0.4 of Git Credential Manager now supports Java 9+. The update is available on GitHub and will be available on Homebrew soon.

**Comment by novak** [comment]
feel free to re-open this issue if version `2.0.4` does not fix this for you.
