### ISSUE TITLE
Can't download https://java.visualstudio.com/Content/RPM-GPG-KEY-olivida.txt

### ISSUE THREAD

**Issue by Yi-Mao** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#73]
Return 404 error

**Comment by vkosilko** [comment]
+1

**Comment by leantk** [comment]
Sorry we recently have been moving our documentation. I added the key to the repo to make sure this doesn't happen in the future. The PR is out here with the addition: https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/pull/75
