### ISSUE TITLE
GCM fails intermittently with Java 8

### ISSUE THREAD

**Issue by james-trimarco** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#76]
Hi all,

I'm using CGM on a Mac running High Sierra 10.13.3. I had the same issue that Joey Herrington raised here, where Java 9 caused GCM to break.

So I uninstalled Java 9 and installed Java 8. That solved the problem for a while, but GCM still stops working occasionally, and throws this error:

```
james$git pull
Fatal: java.lang.Error encountered.  Details:
/usr/bin/security exited with result 51.
stdOut: 
stdErr: 

fatal: credential helper '!/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/bin/java -Ddebug=false -Djava.net.useSystemProxies=true -jar /usr/local/Cellar/git-credential-manager/2.0.3/libexec/git-credential-manager-2.0.3.jar' told us to quit
```

I've tried unstalling java and reinstalling it. Also uninstalled GCM and reinstalled it, but these fixes haven't restored my ability to pull or push to VSTS. Any ideas on what I can do to get this operational again?

**Comment by DavidStaheli** [comment]
Hi @james-trimarco, sorry for the trouble.  A fix is in the works that should also address the error you see.  In the meantime, you can probably skip using GCM and instead, [create a PAT](https://docs.microsoft.com/en-us/vsts/accounts/use-personal-access-tokens-to-authenticate?view=vsts) and use it as your password when prompted by Git (and use any username).

**Comment by dblVs** [comment]
@DavidStaheli any news on this ?

**Comment by novak** [comment]
Version 2.0.4 of GCM was just released, it adds support for Java 9+. It is available now on Github and will be available via Homebrew soon.

Let me know if this issue is still present on the new version.

**Comment by chu01** [comment]
Is there any solution for this issue yet?
