### ISSUE TITLE
credential manager quits on git pull call

### ISSUE THREAD

**Issue by josecelaya** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#85]
```
C02TN1N8GTF1:xxx xxx$ git pull
Fatal: java.lang.Error encountered.  Details:
   unexpected error
fatal: credential helper '!/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java -Ddebug=false -Djava.net.useSystemProxies=true -jar /usr/local/Cellar/git-credential-manager/2.0.3/libexec/git-credential-manager-2.0.3.jar' told us to quit
```

$ java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

On a Mac 10.13.5

Jave installed with Brew

**Comment by thindiyeh** [comment]
getting the same error

**Comment by chcaru** [comment]
Downgrading to JDK 8 fixes this issue. However the documentation on the README is incorrect.

**Comment by whoisj** [comment]
@ All, is there a reason you're choosing to use HTTPS + GCM4ML instead of SSH?

As the maintainer of the GCM (for Windows) [read: not the Java version] I highly recommend that users on Mac and/or Linux rely on SSH instead of HTTP/S when and where possible.

**Comment by chcaru** [comment]
@whoisj I'm almost exclusively a Windows user. I was helping someone on my team set up their dev machine, which was a mac. I did it purely out of habit. Regardless, I think it should still be working if it's supported.

**Comment by whoisj** [comment]
@chcaru I understand, and I do not disagree - I also have no idea who is responsible for this particular package. 😕 I got pulled in because I maintain the GCM for Windows, and this was once a Java clone of that project - they've since drifted significantly, and I've no idea how/what/why this does... well, anything. 😞 

I'll poke around and see if I can find out who can take this issue further, in the meantime I really think SSH is the correct answer.

**Comment by thcase** [comment]
@whoisj You asked why someone was using HTTPS.  It is simple, that is what Visual Studio Online uses.  The credential manager was working fine for at least a year, but now I see the same issues.

**Comment by novak** [comment]
Version 2.0.4 of Git Credential Manager is now available and should resolve this issue. The release is available on GitHub now, and was submitted to homebrew but not available there yet.

**Comment by novak** [comment]
Feel free to re-open this issue if the bug still exists with version `2.0.4`
