### ISSUE TITLE
IllegalArgumentException cloning private GitHub repo

### ISSUE THREAD

**Issue by chriskuech** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#88]
I installed with linuxbrew on Ubuntu 18.04 then tried to clone a private repo and received the following error:
```
Cloning into 'ChrisRepo'...
Fatal: java.lang.IllegalArgumentException encountered.  Details:
tokenSecretStore can't be null
fatal: credential helper '!/home/linuxbrew/.linuxbrew/Cellar/jdk/9.0.4/bin/java -Ddebug=false -Djava.net.useSystemProxies=true -jar /home/linuxbrew/.linuxbrew/Cellar/git-credential-manager/2.0.3/libexec/git-credential-manager-2.0.3.jar' told us to quit
```

I assume this is related to #63 but even if GitHub isn't supported, git-credential-manager should not break GitHub or at a minimum warn in the documentation that it will break github.

**Comment by novak** [comment]
Version 2.0.4 was just released and adds support for Java 9+. This should fix the issue you are seeing. The release is available now on Github and will be available via Homebrew soon.

**Comment by novak** [comment]
Feel free to re-open this issue if the bug still exists in `2.0.4`
